database:
  type: postgresql
  host: localhost
  port: 5432
  database: etl_demo  # Change to your actual database name
  user: etl_user      # Change to your actual username
  password: etl_password  # Change to your actual password
  connection_timeout: 30
  max_retries: 3
  retry_delay: 5

csv:
  input_dir: ./data/input
  archive_dir: ./data/archive
  error_dir: ./data/error
  delimiter: ","
  quotechar: '"'
  encoding: utf-8
  batch_size: 1000

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: ./logs/etl.log
  max_size: 10485760  # 10MB
  backup_count: 5

processing:
  parallel: true
  max_workers: 4
  chunk_size: 10000